import {IndexedDBRepository,SettingsRepository,STORES} from './storage.js';
import {AppService,today,resultOf,stats,pct,validateBackup} from './services.js';
const $=s=>document.querySelector(s), esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const repo=new IndexedDBRepository(),settings=new SettingsRepository(),service=new AppService(repo);
const state={view:'home',data:null,editing:null,detail:null,deckDetail:null,eventDetail:null,source:null};
const labels={home:'HOME',record:'RECORD',events:'EVENTS',decks:'DECKS',analysis:'ANALYSIS'};
const date=x=>x?x.replaceAll('-','/').slice(0,10):'—';
const nameOf=(items,id)=>items.find(x=>x.id===id)?.name||'未設定';
const sortDate=xs=>[...xs].sort((a,b)=>(b.playedAt||b.date||b.createdAt).localeCompare(a.playedAt||a.date||a.createdAt));
const gamesFor=id=>state.data.games.filter(g=>g.matchId===id).sort((a,b)=>a.number-b.number);
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),3500);}
function theme(){const t=settings.get().theme;document.documentElement.dataset.theme=t;}
async function refresh(){state.data=await service.all();render();}
function nav(){return Object.entries(labels).map(([key,label])=>`<button data-nav="${key}" class="${state.view===key?'active':''}" aria-current="${state.view===key?'page':'false'}"><span>${{home:'⌂',record:'＋',events:'▦',decks:'▤',analysis:'◫'}[key]}</span><small>${label}</small></button>`).join('');}
function render(){theme();$('#nav').innerHTML=nav();$('#content').innerHTML=({home:homeView,record:recordView,events:eventsView,decks:decksView,analysis:analysisView,settings:settingsView})[state.view]();$('#content').scrollTop=0;}
function head(k,title,sub){return `<div class="page-head"><div class="eyebrow">${k}</div><h1>${title}</h1><p>${sub}</p></div>`;}
function statCard(title,s){return `<div class="stat-card"><div class="eyebrow">${title}</div><div class="big">${s.rate}</div><div class="muted">${s.total}戦 · ${s.win}勝 ${s.loss}敗 ${s.draw}分</div></div>`;}
function pill(result){return `<span class="pill ${result==='WIN'?'win':result==='DRAW'?'draw':'loss'}">${{WIN:'WIN',LOSS:'LOSS',DRAW:'DRAW',DOUBLE_LOSS:'両敗'}[result]||result}</span>`;}
function battleRow(m){return `<button class="list-row" data-detail="${m.id}"><span class="list-icon">${m.format==='MATCH'?'M':'S'}</span><span class="grow"><b>${esc(nameOf(state.data.decks,m.deckId))} <span class="muted">vs</span> ${esc(m.opponentDeckName)}</b><small>${date(m.playedAt)} · ${esc(nameOf(state.data.events,m.eventId))} · ${m.format}</small></span>${pill(m.result)}<span class="chevron">›</span></button>`;}
function homeView(){const d=state.data,month=today().slice(0,7),recent=sortDate(d.matches),monthly=recent.filter(m=>m.playedAt.slice(0,7)===month),s=stats(monthly.filter(m=>m.format==='MATCH'),d.games.filter(g=>monthly.some(m=>m.id===g.matchId)));const latestDeck=recent[0],event=sortDate(d.events)[0];return `${head('OVERVIEW','戦績を、次の一手へ。','対戦直後の記録から、自分の傾向を見つける。')}<div class="section-title"><h2>今月の記録</h2><span>${month}</span></div><div class="stats-grid">${statCard('MATCH 勝率',s.matches)}${statCard('GAME 勝率',s.games)}</div><button class="primary wide" data-nav="record">＋ 対戦を記録</button><div class="section-title"><h2>最近の使用デッキ</h2></div><div class="card">${latestDeck?`<b>${esc(nameOf(d.decks,latestDeck.deckId))}</b><p class="muted">${esc(d.deckVersions.find(v=>v.id===latestDeck.deckVersionId)?.label||'')} · 最終使用 ${date(latestDeck.playedAt)}</p>`:'まだ対戦記録がありません。'}</div><div class="section-title"><h2>最近のイベント</h2><button class="link" data-nav="events">すべて見る ›</button></div><div class="card">${event?`<b>${esc(event.name)}</b><p class="muted">${date(event.date)} · ${esc(event.venue||event.type)}</p>`:'イベントは未登録です。'}</div><div class="section-title"><h2>対戦履歴</h2></div>${recent.length?recent.slice(0,8).map(battleRow).join(''):'<div class="empty">デッキを登録すると対戦を記録できます。</div>'}`;}
const option=(value,label,selected)=>`<option value="${esc(value)}" ${value===selected?'selected':''}>${esc(label)}</option>`;
const select=(name,items,selected,first='選択してください')=>`<select name="${name}" id="${name}">${option('',first,selected)}${items.map(x=>option(x.id,x.name||x.label,selected)).join('')}</select>`;
function recordView(){const d=state.data,m=d.matches.find(x=>x.id===state.editing),gs=m?gamesFor(m.id):[],format=m?.format||'MATCH',deckId=m?.deckId||d.decks[0]?.id||'',v=d.deckVersions.filter(x=>x.deckId===deckId).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));const game=(n,g)=>`<div class="game-row"><span class="game-no">G${n}</span><div class="seg">${['FIRST','SECOND'].map((x,i)=>`<button type="button" class="${(g?.turn|| (n%2?'FIRST':'SECOND'))===x?'selected':''}" data-game="${n}" data-kind="turn" data-value="${x}">${i?'後攻':'先攻'}</button>`).join('')}</div><div class="seg result">${['WIN','LOSS','DRAW'].map(x=>`<button type="button" class="${g?.result===x?'selected':''}" data-game="${n}" data-kind="result" data-value="${x}">${x==='DRAW'?'分':x==='WIN'?'勝':'負'}</button>`).join('')}</div></div>`;if(!d.decks.length)return `${head('RECORD','対戦を記録','最初に使用デッキを登録してください。')}<button class="primary" data-nav="decks">デッキを登録</button>`;return `${head('RECORD',m?'記録を編集':'対戦を記録','ゲームごとの先後と結果を入力。')}<form id="record-form"><div class="card form-card"><div class="field-grid"><label>対戦日<input name="date" type="date" required value="${esc(m?.playedAt||today())}"></label><label>形式<select name="format" id="format">${option('MATCH','MATCH',format)}${option('SINGLE','SINGLE',format)}</select></label></div><label>使用デッキ${select('deckId',d.decks,m?.deckId||deckId)}</label><label>使用バージョン${select('deckVersionId',v,m?.deckVersionId||v[0]?.id)}</label><label>相手デッキ<input name="opponent" list="opponents" required placeholder="例：エルフェンノーツ" value="${esc(m?.opponentDeckName||'')}"><datalist id="opponents">${[...new Set(d.matches.map(x=>x.opponentDeckName))].map(x=>`<option value="${esc(x)}">`).join('')}</datalist></label><label>イベント${select('eventId',sortDate(d.events),m?.eventId,'イベントなし')}</label></div><div class="section-title"><h2>GAME RESULTS</h2><span id="live-result"></span></div><div id="games" class="card form-card">${Array.from({length:format==='SINGLE'?1:3},(_,i)=>game(i+1,gs[i])).join('')}</div><div class="card form-card"><label>結果の手動修正<select name="override" id="override">${option('','自動判定',m?.resultSource==='manual'?null:'')}${['WIN','LOSS','DRAW','DOUBLE_LOSS'].map((x,i)=>option(x,['勝ち','負け','引き分け','両者敗北'][i],m?.resultSource==='manual'?m.result:null)).join('')}</select></label><small class="muted">ET・ED・投了などによる特殊裁定に使用します。</small><label>タグ <span class="muted">任意・カンマ区切り</span><input name="tags" list="tags-list" placeholder="事故, ET" value="${esc(m?.tags?.join(', ')||'')}"><datalist id="tags-list">${d.tags.map(t=>`<option value="${esc(t.name)}">`).join('')}</datalist></label><label>対戦メモ <span class="muted">任意</span><textarea name="notes" rows="3" placeholder="気づいたことを短く残す">${esc(m?.notes||'')}</textarea></label></div><button class="primary wide" type="submit">${m?'変更を保存':'対戦を保存'}</button>${m?'<button type="button" class="secondary wide" data-cancel-edit>編集をやめる</button>':''}</form>`;}
function field(label,name,value='',attrs=''){return `<label>${label}<input name="${name}" value="${esc(value)}" ${attrs}></label>`;}
function eventsView(){const d=state.data;if(state.eventDetail){const e=d.events.find(x=>x.id===state.eventDetail);if(!e){state.eventDetail=null;return eventsView();}const rows=sortDate(d.matches.filter(m=>m.eventId===e.id)),s=stats(rows.filter(m=>m.format==='MATCH'),d.games.filter(g=>rows.some(m=>m.id===g.matchId)));return `<button class="back" data-back="events">‹ イベント一覧</button>${head('EVENT DETAIL',esc(e.name),`${date(e.date)} · ${esc(e.type)}`)}<div class="stats-grid">${statCard('MATCH',s.matches)}${statCard('GAME',s.games)}</div><div class="card"><p>会場　${esc(e.venue||'—')}</p><p>使用　${esc(nameOf(d.decks,e.deckId))}</p><p>順位　${esc(e.rank||'—')} / ${esc(e.participants||'—')}名</p>${e.notes?`<p class="prewrap">${esc(e.notes)}</p>`:''}</div><div class="section-title"><h2>ラウンド</h2><span>${rows.length}件</span></div>${rows.map((m,i)=>`<div class="round"><span>R${i+1}</span>${battleRow(m)}</div>`).join('')||'<div class="empty">記録はありません。</div>'}`;}
return `${head('EVENTS','イベント','大会単位で対戦をまとめる。')}<details class="card form-card" id="event-create"><summary>＋ イベントを登録</summary><form id="event-form">${field('イベント名','name','','required placeholder="例：ランキングデュエル"')}<div class="field-grid">${field('開催日','date',today(),'type="date" required')}${field('会場','venue','','placeholder="店舗名"')}</div><label>種別<input name="type" list="event-types" value="ランキングデュエル"><datalist id="event-types">${['ランキングデュエル','CS','YCSJ','インストラクターイベント','交流会','フリー','その他',...new Set(state.data.events.map(x=>x.type))].map(x=>`<option value="${esc(x)}">`).join('')}</datalist></label><label>使用デッキ${select('deckId',d.decks,null,'未指定')}</label><div class="field-grid">${field('順位','rank','','placeholder="例：4位"')}${field('参加人数','participants','','type="number" min="1"')}</div><label>メモ<textarea name="notes" rows="2"></textarea></label><button class="primary wide">イベントを保存</button></form></details><div class="section-title"><h2>登録済み</h2><span>${d.events.length}件</span></div>${sortDate(d.events).map(e=>`<button class="list-row" data-event="${e.id}"><span class="list-icon">▦</span><span class="grow"><b>${esc(e.name)}</b><small>${date(e.date)} · ${esc(e.venue||e.type)} · ${d.matches.filter(m=>m.eventId===e.id).length}戦</small></span><span class="chevron">›</span></button>`).join('')||'<div class="empty">イベントは未登録です。</div>'}`;}
const formatCards=xs=>xs?.map(x=>`${x.name} ×${x.count}`).join('\n')||'';
function recipeForm({id='',cards={}}={}){return `<form id="version-form" data-deck="${id}">${field('バージョン名','version',today(),'required placeholder="例：2026.09.24"')}<small class="muted">1行に「カード名 ×枚数」。枚数を省くと1枚です。</small>${['main','extra','side'].map(z=>`<label>${z.toUpperCase()}<textarea name="${z}" rows="4" placeholder="カード名 ×2">${esc(formatCards(cards[z]))}</textarea></label>`).join('')}<label>版のメモ<textarea name="notes" rows="2"></textarea></label><button class="primary wide">${id?'新バージョンを保存':'デッキとレシピを登録'}</button></form>`;}
function decksView(){const d=state.data;if(state.deckDetail){const deck=d.decks.find(x=>x.id===state.deckDetail);if(!deck){state.deckDetail=null;return decksView();}const versions=d.deckVersions.filter(v=>v.deckId===deck.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));return `<button class="back" data-back="decks">‹ デッキ一覧</button>${head('DECK DETAIL',esc(deck.name),esc(deck.type||'デッキタイプ未設定'))}<p class="muted">${esc(deck.notes||'')}</p><div class="section-title"><h2>レシピ履歴</h2><span>${versions.length}版</span></div>${versions.map(v=>`<details class="card recipe"><summary><b>${esc(v.label)}</b><small>${date(v.createdAt)}</small></summary>${['main','extra','side'].map(z=>`<div class="recipe-zone"><b>${z.toUpperCase()} <span>${v.cards[z]?.reduce((n,c)=>n+c.count,0)||0}</span></b>${v.cards[z]?.map(c=>`<div>${esc(c.name)} <span>×${c.count}</span></div>`).join('')||'<p class="muted">未登録</p>'}</div>`).join('')}${v.notes?`<p class="muted prewrap">${esc(v.notes)}</p>`:''}<button class="secondary" data-copy-version="${v.id}">このレシピから新バージョン作成</button></details>`).join('')}<details class="card form-card" id="new-version" ${state.source?'open':''}><summary>＋ 新バージョンを作成</summary>${recipeForm({id:deck.id,cards:d.deckVersions.find(v=>v.id===state.source)?.cards||{}})}</details>`;}
return `${head('DECKS','使用デッキ','構築変更ごとにレシピを保存。')}<details class="card form-card" id="deck-create"><summary>＋ デッキを登録</summary><form id="deck-form">${field('デッキ名','name','','required placeholder="例：烙印"')}${field('デッキタイプ','type','','placeholder="例：融合"')}${field('デッキメモ','deckNotes','','placeholder="運用方針など"')}${recipeForm().replace('<form id="version-form" data-deck="">','<div>').replace('</form>','</div>')}</form></details><div class="section-title"><h2>登録済み</h2><span>${d.decks.length}種</span></div>${d.decks.map(deck=>`<button class="list-row" data-deck-detail="${deck.id}"><span class="list-icon">▤</span><span class="grow"><b>${esc(deck.name)}</b><small>${esc(deck.type||'タイプ未設定')} · ${d.deckVersions.filter(x=>x.deckId===deck.id).length}バージョン · ${d.matches.filter(x=>x.deckId===deck.id).length}戦</small></span><span class="chevron">›</span></button>`).join('')||'<div class="empty">デッキを登録してください。</div>'}`;}
function analysisView(){const d=state.data,all=sortDate(d.matches),dateFrom=$('#analysis-period')?.value||'all';const current=state.period||'all',start=current==='month'?today().slice(0,7)+'-01':current==='30'?new Date(Date.now()-29*864e5).toISOString().slice(0,10):current==='90'?new Date(Date.now()-89*864e5).toISOString().slice(0,10):state.from||'0000-01-01';const end=current==='custom'?(state.to||'9999-12-31'):'9999-12-31',ms=all.filter(m=>m.playedAt>=start&&m.playedAt<=end),gs=d.games.filter(g=>ms.some(m=>m.id===g.matchId)),s=stats(ms.filter(m=>m.format==='MATCH'),gs);const turnStats=x=>{const games=gs.filter(g=>g.turn===x);return stats([],games).games;};const breakdown=(ids,key,label)=>ids.map(id=>{const sub=ms.filter(m=>key(m)===id),g=d.games.filter(x=>sub.some(m=>m.id===x.matchId)),ss=stats(sub.filter(m=>m.format==='MATCH'),g);return `<div class="metric-row"><span>${esc(label(id))}<small>${ss.matches.total} MATCH · ${ss.games.total} GAME</small></span><b>${ss.matches.rate}</b></div>`;}).join('');const deckIds=[...new Set(ms.map(x=>x.deckId))],oppIds=[...new Set(ms.map(x=>x.opponentDeckName))];return `${head('ANALYSIS','成績分析','MATCHとGAMEを分けて集計。')}<div class="card form-card"><label>集計期間<select id="analysis-period">${[['all','全期間'],['month','今月'],['30','直近30日'],['90','直近90日'],['custom','カスタム']].map(([v,l])=>option(v,l,current)).join('')}</select></label>${current==='custom'?`<div class="field-grid"><label>開始<input id="period-from" type="date" value="${esc(state.from||'')}"></label><label>終了<input id="period-to" type="date" value="${esc(state.to||'')}"></label></div>`:''}</div><div class="stats-grid">${statCard('MATCH',s.matches)}${statCard('GAME',s.games)}</div><div class="section-title"><h2>GAME 先後別</h2></div><div class="card">${['FIRST','SECOND'].map((x,i)=>`<div class="metric-row"><span>${i?'後攻':'先攻'}<small>${turnStats(x).total} GAME</small></span><b>${turnStats(x).rate}</b></div>`).join('')}</div><p class="hint">先後は各ゲーム単位。MATCH勝率には先後を割り当てません。</p><div class="section-title"><h2>使用デッキ別</h2></div><div class="card">${breakdown(deckIds,m=>m.deckId,id=>nameOf(d.decks,id))||'<p class="muted">データがありません。</p>'}</div><div class="section-title"><h2>対面別</h2></div><div class="card">${breakdown(oppIds,m=>m.opponentDeckName,id=>id)||'<p class="muted">データがありません。</p>'}</div>`;}
function settingsView(){return `<button class="back" data-nav="home">‹ HOME</button>${head('SETTINGS','設定','表示とデータの管理。')}<div class="card form-card"><label>外観<select id="theme">${['system','dark','light'].map((x,i)=>option(x,['SYSTEM','DARK','LIGHT'][i],settings.get().theme)).join('')}</select></label></div><div class="section-title"><h2>バックアップ</h2></div><div class="card form-card"><p class="muted">データはこの端末のブラウザ内に保存されます。定期的にJSONを保存してください。</p><button class="secondary wide" id="export">JSONをエクスポート</button><label class="file-btn">JSONから復元<input type="file" id="import-file" accept="application/json,.json"></label><p class="muted small">復元時に「上書き」または「マージ」を選べます。同じIDはインポート側を採用します。</p></div>`;}
function download(content,filename,type){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([content],{type}));a.href=url;a.download=filename;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function dialog(html){let el=$('#dialog');if(!el){el=document.createElement('dialog');el.id='dialog';document.body.append(el);}el.innerHTML=html;el.showModal();return el;}
function detail(id){const m=state.data.matches.find(x=>x.id===id);if(!m)return;const v=state.data.deckVersions.find(x=>x.id===m.deckVersionId),gs=gamesFor(id);dialog(`<div class="dialog-head"><span class="eyebrow">${m.format} · ${date(m.playedAt)}</span><button class="icon-button" data-close aria-label="閉じる">×</button></div><h2>${esc(nameOf(state.data.decks,m.deckId))} <span class="muted">vs</span> ${esc(m.opponentDeckName)}</h2><p>${pill(m.result)} <span class="muted">${m.resultSource==='manual'?'手動判定':'自動判定'}</span></p><p class="muted">${esc(nameOf(state.data.events,m.eventId))} · ${esc(v?.label||'')}</p>${gs.map(g=>`<div class="metric-row"><span>GAME ${g.number} · ${g.turn==='FIRST'?'先攻':'後攻'}</span>${pill(g.result)}</div>`).join('')}${m.tags.length?`<p>${m.tags.map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</p>`:''}${m.notes?`<p class="prewrap note">${esc(m.notes)}</p>`:''}<div class="dialog-actions"><button class="secondary" data-edit="${id}">編集</button><button class="danger" data-delete="${id}">削除</button></div>`);}
function live(){const rows=[...document.querySelectorAll('.game-row')].filter(x=>x.style.display!=='none');const gs=rows.map(x=>({result:x.querySelector('[data-kind=result].selected')?.dataset.value})).filter(x=>x.result);const manual=$('#override')?.value;$('#live-result').textContent=manual?`手動: ${manual}`:gs.length?`自動: ${resultOf(gs)}`:'結果を選択';}
function changeFormat(){const single=$('#format').value==='SINGLE';document.querySelectorAll('.game-row').forEach((x,i)=>{x.style.display=single&&i>0?'none':'';});live();}
async function submit(form){const f=new FormData(form),id=form.id;try{if(id==='deck-form'){await service.addDeck({name:f.get('name'),type:f.get('type'),notes:f.get('deckNotes'),version:f.get('version'),main:f.get('main'),extra:f.get('extra'),side:f.get('side')});toast('デッキを登録しました');state.view='decks';}else if(id==='version-form'){await service.addVersion(form.dataset.deck,Object.fromEntries(f));toast('新バージョンを保存しました');state.source=null;}else if(id==='event-form'){await service.addEvent(Object.fromEntries(f));toast('イベントを登録しました');}else if(id==='record-form'){const rows=[...document.querySelectorAll('.game-row')].filter(x=>x.style.display!=='none');const games=rows.map(x=>({turn:x.querySelector('[data-kind=turn].selected')?.dataset.value,result:x.querySelector('[data-kind=result].selected')?.dataset.value}));await service.saveBattle({date:f.get('date'),format:f.get('format'),deckId:f.get('deckId'),deckVersionId:f.get('deckVersionId'),opponent:f.get('opponent'),eventId:f.get('eventId'),games,override:f.get('override'),tags:f.get('tags'),notes:f.get('notes')},state.editing);toast('対戦を保存しました');state.editing=null;state.view='home';}await refresh();}catch(e){toast(e.message||'保存に失敗しました');}}
document.addEventListener('submit',e=>{if(['deck-form','version-form','event-form','record-form'].includes(e.target.id)){e.preventDefault();submit(e.target);}});
document.addEventListener('click',async e=>{const target=e.target.closest('button');if(!target)return;const d=target.dataset;
 if(d.nav){state.view=d.nav;state.editing=null;state.eventDetail=null;state.deckDetail=null;state.source=null;render();return;}
 if(target.id==='settings-btn'){state.view='settings';render();return;}
 if(d.back){if(d.back==='events')state.eventDetail=null;else state.deckDetail=null;state.source=null;render();return;}
 if(d.detail){detail(d.detail);return;}
 if(d.event){state.eventDetail=d.event;render();return;}
 if(d.deckDetail){state.deckDetail=d.deckDetail;render();return;}
 if(d.copyVersion){state.source=d.copyVersion;render();$('#new-version')?.scrollIntoView({behavior:'smooth',block:'start'});return;}
 if(d.game){const group=target.closest('.seg');group.querySelectorAll('button').forEach(b=>b.classList.remove('selected'));target.classList.add('selected');live();return;}
 if(d.close!==undefined){$('#dialog').close();return;}
 if(d.edit){$('#dialog').close();state.editing=d.edit;state.view='record';render();return;}
 if(d.delete){if(!confirm('この対戦記録と各ゲームを削除しますか？'))return;try{await service.deleteBattle(d.delete);$('#dialog').close();toast('記録を削除しました');await refresh();}catch(err){toast(err.message);}return;}
 if(d.cancelEdit!==undefined){state.editing=null;render();return;}
 if(target.id==='export'){download(JSON.stringify(await service.exportBackup(),null,2),`ocg-record-backup-${today().replaceAll('-','')}.json`,'application/json');toast('バックアップを保存しました');}
});
document.addEventListener('change',async e=>{const t=e.target;
 if(t.id==='deckId'&&state.view==='record'){const versions=state.data.deckVersions.filter(v=>v.deckId===t.value).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));$('#deckVersionId').innerHTML=versions.map(v=>option(v.id,v.label,versions[0]?.id)).join('');}
 if(t.id==='format'){changeFormat();}
 if(t.id==='override')live();
 if(t.id==='analysis-period'){state.period=t.value;render();}
 if(t.id==='period-from'||t.id==='period-to'){state[t.id==='period-from'?'from':'to']=t.value;render();}
 if(t.id==='theme'){settings.save({theme:t.value});theme();}
 if(t.id==='import-file'&&t.files[0]){try{const data=validateBackup(JSON.parse(await t.files[0].text()));const counts=STORES.map(s=>`${s}: ${data[s].length}`).join(' / ');const modal=dialog(`<h2>バックアップを復元</h2><p class="muted">${esc(counts)}</p><p>上書きすると現在のデータを消去します。マージは同じIDのデータを読み込んだ内容で更新します。</p><div class="dialog-actions"><button class="secondary" data-import="merge">マージ</button><button class="danger" data-import="replace">上書き</button><button class="secondary" data-close>キャンセル</button></div>`);modal.onclick=async ev=>{const mode=ev.target.closest('[data-import]')?.dataset.import;if(!mode)return;try{await service.importBackup(data,mode);modal.close();toast('復元しました');await refresh();}catch(err){toast(err.message||'復元に失敗しました');}};}catch(err){toast(err.message||'JSONを読み込めません');}t.value='';}
});
try{await repo.ready;await refresh();}catch(e){$('#content').innerHTML=`<div class="empty">データベースを開けません。ブラウザのプライベートモードやストレージ設定をご確認ください。<br>${esc(e.message)}</div>`;}
