import {IndexedDBRepository,SettingsRepository,STORES} from './storage.js';
import {AppService,today,resultOf,stats,validateBackup,parseCards} from './services.js';
import {analyze,battlesCsv} from './analysisService.js';
import {renderAnalysis} from './analysisView.js';
import {readDeckPdf} from './pdfImport.js';
import {allPeriods,regulationLabel,regulationForDate} from './defaultPeriods.js';
import {searchDecksByCard} from './deckSearch.js';
import {matchingDecks,sortedDecks,versionsForDeck} from './deckSelection.js';
import {lastUsedRecord,recordDateDefaults} from './recordDefaults.js';
import {opponentNames,suggestOpponents} from './opponentSuggestions.js';
import {eventOptionLabel,eventRecipeVersion} from './eventLinks.js';
import {groupCards,formatCards} from './cardTypes.js';
import {icon} from './icons.js';
import {CloudController,cloudConfig,saveCloudConfig} from './cloud.js';
const $=s=>document.querySelector(s), esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const repo=new IndexedDBRepository(),settings=new SettingsRepository(),service=new AppService(repo),cloud=new CloudController(repo);
const state={view:'home',data:null,editing:null,detail:null,deckDetail:null,eventDetail:null,editingEvent:false,originEvent:null,focusVersion:null,eventVenue:'',venue:'',source:null,pdfDraft:null,cardSearch:'',cloudError:''};
const labels={home:'HOME',record:'RECORD',events:'EVENTS',decks:'DECKS',analysis:'ANALYSIS'};
const date=x=>x?x.replaceAll('-','/').slice(0,10):'—';
const nameOf=(items,id)=>items.find(x=>x.id===id)?.name||'未設定';
const chronology=x=>x.playedAt||x.date||x.createdAt;
const sortDate=xs=>[...xs].sort((a,b)=>chronology(b).localeCompare(chronology(a)));
const battleDate=m=>date(m.playedAt);
const regulations=()=>allPeriods(state.data.periods).sort((a,b)=>b.startDate.localeCompare(a.startDate));
const regulationName=id=>id?regulationLabel(regulations().find(p=>p.id===id)?.startDate):'未設定';
const regulationSelect=(selected,dateValue=today())=>`<label>レギュレーション<select name="regulationId" id="regulationId">${option('','未指定',selected)}${regulations().map(p=>option(p.id,regulationLabel(p.startDate),selected??regulationForDate(dateValue,state.data.periods)?.id)).join('')}</select></label>`;
const gamesFor=id=>state.data.games.filter(g=>g.matchId===id).sort((a,b)=>a.number-b.number);
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),3500);}
let syncTimer;
function cloudStatus(){return cloud.busy?'同期中…':state.cloudError?`エラー：${esc(state.cloudError)}`:cloud.user?`ログイン中：${esc(cloud.user.email||'アカウント')} · 最終同期 ${esc(cloud.lastSync?.replace('T',' ').slice(0,16)||'まだありません')}`:cloud.client?'未ログイン':'クラウド未設定';}
let observedCloudUser=null,observedCloudReady=false;
cloud.onChange(()=>{const id=cloud.user?.id||null,ready=!!cloud.client,changed=id!==observedCloudUser||ready!==observedCloudReady;
 if(id&&id!==observedCloudUser)scheduleCloudSync();observedCloudUser=id;observedCloudReady=ready;
 if(changed&&state.data&&state.view==='settings')render();else{const status=$('#cloud-status');if(status)status.innerHTML=cloudStatus();}});
async function runCloudSync(){if(!cloud.user||cloud.busy)return;try{state.cloudError='';const result=await cloud.sync();state.data=await service.all();if(state.view!=='record'&&!document.activeElement?.closest('form'))render();if(result.conflicts)toast(`同期完了：${result.conflicts}件の競合を更新日時で解決しました`);}catch(error){state.cloudError=error.message||'同期に失敗しました';cloud.listener();toast(state.cloudError);}}
function scheduleCloudSync(){if(!cloud.user)return;clearTimeout(syncTimer);syncTimer=setTimeout(runCloudSync,800);}
function theme(){const t=settings.get().theme;document.documentElement.dataset.theme=t;}
async function refresh(){state.data=await service.all();render();}
function nav(){return Object.entries(labels).map(([key,label])=>`<button data-nav="${key}" class="${state.view===key?'active':''}" aria-current="${state.view===key?'page':'false'}">${icon(key)}<small>${label}</small></button>`).join('');}
function render(){theme();$('#nav').innerHTML=nav();$('#content').innerHTML=({home:homeView,record:recordView,events:eventsView,decks:decksView,analysis:analysisView,settings:settingsView})[state.view]();window.scrollTo(0,0);}
function head(k,title,sub){const art=({OVERVIEW:'home',RECORD:'record',EVENTS:'events','EVENT DETAIL':'events',DECKS:'decks','DECK DETAIL':'decks',ANALYSIS:'analysis',SETTINGS:'settings'})[k];return `<div class="page-head illustrated"><div class="page-head-copy"><div class="eyebrow">${k}</div><h1>${title}</h1><p>${sub}</p></div>${art?`<img class="page-art" src="./assets/${art}.svg" alt="" loading="lazy" decoding="async">`:''}</div>`;}
function statCard(title,s){return `<div class="stat-card"><div class="eyebrow">${title}</div><div class="big">${s.rate}</div><div class="muted">${s.total}戦 · ${s.win}勝 ${s.loss}敗 ${s.draw}分</div></div>`;}
function pill(result){return `<span class="pill ${result==='WIN'?'win':result==='DRAW'?'draw':'loss'}">${{WIN:'WIN',LOSS:'LOSS',DRAW:'DRAW',DOUBLE_LOSS:'両敗'}[result]||result}</span>`;}
function battleRow(m){return `<button class="list-row" data-detail="${m.id}"><span class="list-icon">${icon('record')}</span><span class="grow"><b>${esc(nameOf(state.data.decks,m.deckId))} <span class="muted">vs</span> ${esc(m.opponentDeckName)}</b><small>${battleDate(m)} · ${esc(nameOf(state.data.events,m.eventId))} · ${m.format}</small></span>${pill(m.result)}<span class="chevron">›</span></button>`;}
function homeView(){const d=state.data,month=today().slice(0,7),recent=sortDate(d.matches),monthly=recent.filter(m=>m.playedAt.slice(0,7)===month),s=stats(monthly.filter(m=>m.format==='MATCH'),d.games.filter(g=>monthly.some(m=>m.id===g.matchId)));const latestDeck=recent[0],event=sortDate(d.events)[0];return `${head('OVERVIEW','戦績を、次の一手へ。','対戦直後の記録から、自分の傾向を見つける。')}<div class="section-title"><h2>今月の記録</h2><span>${month}</span></div><div class="stats-grid">${statCard('MATCH 勝率',s.matches)}${statCard('GAME 勝率',s.games)}</div><button class="primary wide" data-nav="record">＋ 対戦を記録</button><div class="section-title"><h2>最近の使用デッキ</h2></div><div class="card media-card"><img src="./assets/decks.svg" alt="" loading="lazy"> <div>${latestDeck?`<b>${esc(nameOf(d.decks,latestDeck.deckId))}</b><p class="muted">${esc(d.deckVersions.find(v=>v.id===latestDeck.deckVersionId)?.label||'レシピ未登録')} · 最終使用 ${date(latestDeck.playedAt)}</p>`:'まだ対戦記録がありません。'}</div></div><div class="section-title"><h2>最近のイベント</h2><button class="link" data-nav="events">すべて見る ›</button></div><div class="card media-card"><img src="./assets/events.svg" alt="" loading="lazy"><div>${event?`<b>${esc(event.name)}</b><p class="muted">${date(event.date)} · ${esc(event.venue||'店舗未設定')}</p>`:'イベントは未登録です。'}</div></div><div class="section-title"><h2>対戦履歴</h2></div>${recent.length?recent.slice(0,8).map(battleRow).join(''):'<div class="empty">デッキを登録すると対戦を記録できます。</div>'}`;}
const option=(value,label,selected)=>`<option value="${esc(value)}" ${value===selected?'selected':''}>${esc(label)}</option>`;
const select=(name,items,selected,first='選択してください')=>`<select name="${name}" id="${name}">${option('',first,selected)}${items.map(x=>option(x.id,x.name||x.label,selected)).join('')}</select>`;
function comboField(kind,label,value,options){
 const placeholder=kind==='deck'?'デッキ名を入力または選択':'入力または候補を選択';
 const buttons=options.map(item=>`<button type="button" role="option" data-combo-option="${kind}" data-combo-name="${esc(item.name)}" data-combo-id="${esc(item.id||'')}"><span class="combo-option-name">${esc(item.name)}</span>${item.meta?`<small>${esc(item.meta)}</small>`:''}</button>`).join('');
 return `<div class="combo-wrap" data-combo="${kind}"><label for="${kind}">${label}</label><div class="typeahead-combo"><input name="${kind==='deck'?'deckName':'opponent'}" id="${kind}" role="combobox" aria-controls="${kind}-options" aria-expanded="false" aria-autocomplete="list" autocomplete="off" required placeholder="${placeholder}" value="${esc(value)}"><button type="button" id="${kind}-toggle" data-combo-toggle="${kind}" aria-label="${label}の候補を表示" aria-controls="${kind}-options" aria-expanded="false">⌄</button></div><div id="${kind}-options" class="opponent-options" role="listbox" hidden>${buttons||'<p class="muted">候補はまだありません。名前を入力してください。</p>'}</div><small class="combo-hint" id="${kind}-hint">入力すると候補を絞り込めます。</small></div>`;
}
function recordView(){
 const d=state.data,m=d.matches.find(x=>x.id===state.editing),last=lastUsedRecord(d.matches),previous=m?null:last;
 const turns=previous?gamesFor(previous.id):[],gs=m?gamesFor(m.id):turns.map(g=>({turn:g.turn}));
 const format=m?.format||previous?.format||'MATCH',dateDefaults=recordDateDefaults(m,previous);
 const preferred=m?.deckId||previous?.deckId||d.decks[0]?.id||'';
 const deck=d.decks.find(x=>x.id===preferred),versions=deck?versionsForDeck(d.deckVersions,deck.id):[];
 const legacyUnversioned=!!m&&m.deckId===deck?.id&&!m.deckVersionId&&versions.length>0;
 const versionId=legacyUnversioned?'':m?.deckVersionId||versions.find(v=>v.id===previous?.deckVersionId)?.id||versions[0]?.id||'';
 const deckOptions=sortedDecks(d.decks).map(x=>({id:x.id,name:x.name,meta:`${d.deckVersions.filter(v=>v.deckId===x.id).length}版 · ${regulationName(x.regulationId)}`}));
 const opponentOptions=opponentNames(d.matches).map(name=>({name}));
 const eventChoices=sortDate(d.events).map(e=>({...e,name:eventOptionLabel(e)}));
 const game=(n,g)=>`<div class="game-row"><span class="game-no">G${n}</span><div class="seg">${['FIRST','SECOND'].map((x,i)=>`<button type="button" class="${(g?.turn||(n%2?'FIRST':'SECOND'))===x?'selected':''}" data-game="${n}" data-kind="turn" data-value="${x}">${i?'後攻':'先攻'}</button>`).join('')}</div><div class="seg result">${['WIN','LOSS','DRAW'].map(x=>`<button type="button" class="${g?.result===x?'selected':''}" data-game="${n}" data-kind="result" data-value="${x}">${x==='DRAW'?'分':x==='WIN'?'勝':'負'}</button>`).join('')}</div></div>`;
 return `${head('RECORD',m?'記録を編集':'対戦を記録','デッキ名と結果を入力。未登録のデッキも記録できます。')}<form id="record-form"><div class="card form-card"><div class="field-grid record-meta-grid"><label>対戦日<input name="date" type="date" required value="${esc(dateDefaults.date)}"></label><label>形式<select name="format" id="format">${option('MATCH','MATCH',format)}${option('SINGLE','SINGLE',format)}</select></label></div>${comboField('deck','使用デッキ',deck?.name||'',deckOptions)}<input type="hidden" name="deckId" id="deckId" value="${esc(deck?.id||'')}"><label>使用バージョン<select name="deckVersionId" id="deckVersionId" ${versions.length?'':'disabled'}>${versions.length?(legacyUnversioned?option('','対戦当時はレシピ未登録',''):'')+versions.map(v=>option(v.id,v.label,versionId)).join(''):option('','レシピ未登録（選択不要）','')}</select></label><small class="muted" id="deck-version-hint">${versions.length?`${versions.length}件のレシピから選択できます。`:'レシピがないデッキも版なしで保存できます。'}</small>${comboField('opponent','相手デッキ',m?.opponentDeckName||'',opponentOptions)}<label>イベント${select('eventId',eventChoices,m?.eventId||previous?.eventId,'イベントなし')}</label></div><div class="section-title"><h2>GAME RESULTS</h2><span id="live-result"></span></div><div id="games" class="card form-card">${Array.from({length:format==='SINGLE'?1:3},(_,i)=>game(i+1,gs[i])).join('')}</div><div class="card form-card"><label>結果の手動修正<select name="override" id="override">${option('','自動判定',m?.resultSource==='manual'?null:'')}${['WIN','LOSS','DRAW','DOUBLE_LOSS'].map((x,i)=>option(x,['勝ち','負け','引き分け','両者敗北'][i],m?.resultSource==='manual'?m.result:null)).join('')}</select></label><small class="muted">ET・ED・投了などによる特殊裁定に使用します。</small><label>タグ <span class="muted">任意・カンマ区切り</span><input name="tags" list="tags-list" placeholder="事故, ET" value="${esc(m?.tags?.join(', ')||'')}"><datalist id="tags-list">${d.tags.map(t=>`<option value="${esc(t.name)}">`).join('')}</datalist></label><label>対戦メモ <span class="muted">任意</span><textarea name="notes" rows="3" placeholder="気づいたことを短く残す">${esc(m?.notes||'')}</textarea></label></div><button class="primary wide" type="submit">${m?'変更を保存':'対戦を保存'}</button>${m?'<button type="button" class="secondary wide" data-cancel-edit>編集をやめる</button>':''}</form>`;
}
function field(label,name,value='',attrs=''){return `<label>${label}<input name="${name}" value="${esc(value)}" ${attrs}></label>`;}
function eventFields(e={},venues=[]){return `${field('イベント名','name',e.name||'','required placeholder="例：ランキングデュエル"')}<div class="field-grid">${field('開催日','date',e.date||today(),'type="date" required')}${field('店舗','venue',e.venue||'','list="venues" placeholder="店舗名を選択または入力"')}<datalist id="venues">${venues.map(v=>`<option value="${esc(v)}">`).join('')}</datalist></div>${regulationSelect(e.id?(e.regulationId||''):null,e.date||today())}<label>使用デッキ${select('deckId',state.data.decks,e.deckId||null,'未指定')}</label><div class="field-grid">${field('順位','rank',e.rank||'','placeholder="例：4位"')}${field('参加人数','participants',e.participants||'','type="number" min="1"')}</div><label>メモ<textarea name="notes" rows="2">${esc(e.notes||'')}</textarea></label>`;}
function eventsView(){const d=state.data;if(state.eventDetail){const e=d.events.find(x=>x.id===state.eventDetail);if(!e){state.eventDetail=null;return eventsView();}const rows=sortDate(d.matches.filter(m=>m.eventId===e.id)),venues=[...new Set(d.events.map(x=>x.venue?.trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ja')),s=stats(rows.filter(m=>m.format==='MATCH'),d.games.filter(g=>rows.some(m=>m.id===g.matchId)));return `<button class="back" data-back="events">‹ イベント一覧</button>${head('EVENT DETAIL',esc(e.name),`${date(e.date)}${e.venue?' · '+esc(e.venue):''}`)}<div class="stats-grid">${statCard('MATCH',s.matches)}${statCard('GAME',s.games)}</div>${state.editingEvent?`<div class="card form-card"><h2>イベント内容を編集</h2><form id="event-edit-form" data-event="${e.id}">${eventFields(e,venues)}<button class="primary wide">変更を保存</button><button type="button" class="secondary wide" data-cancel-event-edit>キャンセル</button></form></div>`:`<div class="card"><p>店舗　${esc(e.venue||'—')}</p><p>レギュレーション　${esc(regulationName(e.regulationId))}</p><div class="event-deck-link"><img src="./assets/decks.svg" alt="" loading="lazy"><span>使用デッキ<br><b>${esc(nameOf(d.decks,e.deckId))}</b></span>${e.deckId&&d.decks.some(deck=>deck.id===e.deckId)?`<button type="button" class="secondary" data-event-deck="${e.deckId}">${icon('decks')} レシピを確認</button>`:''}</div><p>順位　${esc(e.rank||'—')} / ${esc(e.participants||'—')}名</p>${e.notes?`<p class="prewrap">${esc(e.notes)}</p>`:''}<button type="button" class="secondary" data-edit-event>イベントを編集</button></div>`}<div class="section-title"><h2>ラウンド</h2><span>${rows.length}件</span></div>${rows.map((m,i)=>`<div class="round"><span>R${i+1}</span>${battleRow(m)}</div>`).join('')||'<div class="empty">記録はありません。</div>'}`;}
const venues=[...new Set(d.events.map(e=>e.venue?.trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ja')),selected=state.eventVenue,filteredEvents=d.events.filter(e=>!selected||e.venue===selected),venueMatches=selected?sortDate(d.matches.filter(m=>d.events.some(e=>e.id===m.eventId&&e.venue===selected))):[];return `${head('EVENTS','イベント','大会単位で対戦をまとめる。')}<details class="card form-card" id="event-create"><summary>＋ イベントを登録</summary><form id="event-form">${eventFields({},venues)}<button class="primary wide">イベントを保存</button></form></details><div class="card form-card"><label>店舗で対戦履歴を探す<select id="event-venue">${option('','すべての店舗',selected)}${venues.map(v=>option(v,v,selected)).join('')}</select></label></div>${selected?`<div class="section-title"><h2>${esc(selected)}での対戦</h2><span>${venueMatches.length}件</span></div>${venueMatches.map(battleRow).join('')||'<div class="empty">対戦記録はありません。</div>'}`:''}<div class="section-title"><h2>登録済み</h2><span>${filteredEvents.length}件</span></div>${sortDate(filteredEvents).map(e=>`<button class="list-row" data-event="${e.id}"><span class="list-icon">${icon('events')}</span><span class="grow"><b>${esc(e.name)}</b><small>${date(e.date)} · ${esc(regulationName(e.regulationId))} · ${esc(e.venue||'店舗未設定')} · ${d.matches.filter(m=>m.eventId===e.id).length}戦</small></span><span class="chevron">›</span></button>`).join('')||'<div class="empty empty-illustrated"><img src="./assets/events.svg" alt="">イベントは未登録です。</div>'}`;}
function recipeForm({id='',cards={}}={}){const total=z=>cards[z]?.reduce((n,c)=>n+c.count,0)||0;return `<form id="version-form" data-deck="${id}">${field('バージョン名','version',today(),'required placeholder="例：2026.09.24"')}<small class="muted">【モンスター】【魔法】【罠】などの見出しの下に、1行ずつ「枚数《カード名》」を入力します。種別未指定は未分類になります。</small>${['main','extra','side'].map(z=>`<label>${z.toUpperCase()}<textarea name="${z}" rows="4" placeholder="1《烙印融合》">${esc(formatCards(cards[z]))}</textarea></label>`).join('')}<div class="recipe-counts" role="status">編集中の枚数：MAIN ${total('main')} / EXTRA ${total('extra')} / SIDE ${total('side')}</div><button class="primary wide">${id?'新バージョンを保存':'デッキとレシピを登録'}</button></form>`;}
function pdfPicker(){return `<label class="file-btn">公式サイト発行PDFから読み込む<input id="deck-pdf-file" type="file" accept=".pdf,application/pdf"></label>`;}
function pdfPreview(draft){return draft?`<div class="import-preview"><b>読み込み結果を確認してください</b><small>${esc(draft.filename)} · PDF読取時 MAIN ${draft.totals.main} / EXTRA ${draft.totals.extra} / SIDE ${draft.totals.side}</small>${draft.warnings.length?`<div class="import-warning">${draft.warnings.map(w=>`<p>${esc(w)}</p>`).join('')}</div>`:''}<p>カード名・枚数を確認し、必要なら下の欄を修正して保存してください。PDF自体は保存しません。</p></div>`:'';}
function decksView(){const d=state.data;if(state.deckDetail){const deck=d.decks.find(x=>x.id===state.deckDetail);if(!deck){state.deckDetail=null;return decksView();}const versions=d.deckVersions.filter(v=>v.deckId===deck.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)),draft=state.pdfDraft?.deckId===deck.id?state.pdfDraft:null;return `<button class="back" data-back="${state.originEvent?'event-detail':'decks'}">‹ ${state.originEvent?'イベント詳細':'デッキ一覧'}</button>${head('DECK DETAIL',esc(deck.name),`レギュレーション ${esc(regulationName(deck.regulationId))} · レシピのバージョン履歴`)}<div class="section-title"><h2>レシピ履歴</h2><span>${versions.length}版</span></div>${versions.length?'':`<div class="card empty">レシピはまだありません。下からこのデッキの新バージョンを作成できます。</div>`}${versions.map(v=>`<details class="card recipe" ${state.focusVersion===v.id?'open':''}><summary><b>${esc(v.label)}</b><small>${date(v.createdAt)}</small></summary>${['main','extra','side'].map(z=>`<div class="recipe-zone"><b>${z.toUpperCase()} <span>${v.cards[z]?.reduce((n,c)=>n+c.count,0)||0}</span></b>${groupCards(v.cards[z]).map(group=>`<div class="card-kind card-kind-${group.type.toLowerCase()}"><div class="card-kind-title">${icon(group.type.toLowerCase())}<b>${group.label}</b><small>${group.cards.reduce((sum,c)=>sum+c.count,0)}枚</small></div>${group.cards.map(c=>`<button type="button" class="recipe-card-link" data-card-search="${esc(c.name)}" title="このカードを採用したデッキを探す">${c.count}《${esc(c.name)}》</button>`).join('')}</div>`).join('')||'<p class="muted">未登録</p>'}</div>`).join('')}<button class="secondary" data-copy-version="${v.id}">このレシピから新バージョン作成</button></details>`).join('')}<details class="card form-card" id="new-version" ${state.source||draft?'open':''}><summary>＋ 新バージョンを作成</summary>${pdfPicker()}${pdfPreview(draft)}${recipeForm({id:deck.id,cards:draft?.cards||d.deckVersions.find(v=>v.id===state.source)?.cards||{}})}</details>`;}
const draft=state.pdfDraft?.deckId===null?state.pdfDraft:null,searchResults=searchDecksByCard(d.decks,d.deckVersions,state.cardSearch);return `${head('DECKS','使用デッキ','構築変更ごとにレシピを保存。')}<details class="card form-card" id="deck-create" ${draft?'open':''}><summary>＋ デッキを登録 / PDFから取り込む</summary>${pdfPicker()}${pdfPreview(draft)}<form id="deck-form">${field('デッキ名','name',draft?.suggestedName||'','required placeholder="例：烙印"')}${regulationSelect(null,today())}${recipeForm({cards:draft?.cards||{}}).replace('<form id="version-form" data-deck="">','<div>').replace('</form>','</div>')}</form></details><div class="card form-card"><label>採用カードでデッキを検索<input id="deck-card-search" list="known-cards" type="search" value="${esc(state.cardSearch)}" placeholder="カード名を入力"><datalist id="known-cards">${[...new Set(d.deckVersions.flatMap(v=>Object.values(v.cards||{}).flatMap(xs=>(xs||[]).map(c=>c.name))))].sort((a,b)=>a.localeCompare(b,'ja')).map(n=>`<option value="${esc(n)}">`).join('')}</datalist></label><small class="muted">MAIN・EXTRA・SIDEの全バージョンを対象に検索します。</small></div><div class="section-title"><h2>登録済み</h2><span>${searchResults.length}種</span></div>${searchResults.map(({deck,hits})=>`<button class="list-row" data-deck-detail="${deck.id}"><span class="list-icon">${icon('decks')}</span><span class="grow"><b>${esc(deck.name)}</b><small>${esc(regulationName(deck.regulationId))} · ${d.deckVersions.filter(x=>x.deckId===deck.id).length}バージョン · ${d.matches.filter(x=>x.deckId===deck.id).length}戦${state.cardSearch?` · ${hits.map(({version,zone,card})=>`${esc(version.label)} ${zone.toUpperCase()} ${card.count}《${esc(card.name)}》`).join(' / ')}`:''}</small></span><span class="chevron">›</span></button>`).join('')||`<div class="empty">${state.cardSearch?'該当するカードを採用したデッキはありません。':'デッキを登録してください。'}</div>`}`;}
function analysisView(){return renderAnalysis(state.data,state);}
function settingsView(){const cfg=cloudConfig();return `<button class="back" data-nav="home">‹ HOME</button>${head('SETTINGS','設定','表示とデータの管理。')}<div class="card form-card"><label>外観<select id="theme">${['system','dark','light'].map((x,i)=>option(x,['SYSTEM','DARK','LIGHT'][i],settings.get().theme)).join('')}</select></label></div><div class="section-title"><h2>クラウド同期</h2></div><div class="card form-card"><p class="muted small">SupabaseのプロジェクトURLと公開キーを設定すると、メールでログインし、複数端末で同期できます。クラウド設定はこのブラウザに保存します。</p><form id="cloud-config-form"><label>プロジェクトURL<input name="url" type="url" required placeholder="https://xxxx.supabase.co" value="${esc(cfg?.url||'')}"></label><label>公開キー（publishable / anon）<input name="key" required autocomplete="off" placeholder="sb_publishable_..." value="${esc(cfg?.key||'')}"></label><button class="secondary wide" type="submit">接続先を保存</button></form><p class="muted" id="cloud-status" role="status">${cloudStatus()}</p>${cloud.user?`<button class="primary wide" id="cloud-sync" ${cloud.busy?'disabled':''}>今すぐ同期</button><button class="secondary wide" id="cloud-signout">ログアウト</button>`:cloud.client?`<form id="cloud-login-form"><label>メールアドレス<input name="email" type="email" autocomplete="email" required placeholder="you@example.com"></label><button class="primary wide" type="submit">ログイン用リンクを送信</button></form>`:''}<p class="muted small">ログアウトしても端末の記録は残ります。端末を共有する場合は、バックアップ後に端末データを消去してください。</p><button class="secondary wide" id="cloud-reset-device">端末データと同期履歴を消去</button></div><div class="section-title"><h2>バックアップ</h2></div><div class="card form-card"><p class="muted">データはこの端末のブラウザ内に保存されます。定期的にJSONを保存してください。</p><button class="secondary wide" id="export">JSONをエクスポート</button><label class="file-btn">JSONから復元<input type="file" id="import-file" accept="application/json,.json"></label><p class="muted small">復元時に「上書き」または「マージ」を選べます。同じIDはインポート側を採用します。</p></div><div class="section-title"><h2>データの削除</h2></div><div class="card form-card"><p class="muted">対戦、デッキ、イベント、独自のレギュレーション、表示設定を削除します。ログイン中は次回同期時にクラウド上の記録も削除します。復元には事前のJSONバックアップが必要です。</p><button class="danger wide" id="clear-all">保存データをすべて削除</button></div>`;}
function download(content,filename,type){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([content],{type}));a.href=url;a.download=filename;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function dialog(html){let el=$('#dialog');if(!el){el=document.createElement('dialog');el.id='dialog';document.body.append(el);}el.innerHTML=html;el.showModal();return el;}
function detail(id){const m=state.data.matches.find(x=>x.id===id);if(!m)return;const v=state.data.deckVersions.find(x=>x.id===m.deckVersionId),gs=gamesFor(id);dialog(`<div class="dialog-head"><span class="eyebrow">${m.format} · ${battleDate(m)}</span><button class="icon-button" data-close aria-label="閉じる">×</button></div><h2>${esc(nameOf(state.data.decks,m.deckId))} <span class="muted">vs</span> ${esc(m.opponentDeckName)}</h2><p>${pill(m.result)} <span class="muted">${m.resultSource==='manual'?'手動判定':'自動判定'}</span></p><p class="muted">${esc(nameOf(state.data.events,m.eventId))} · ${esc(v?.label||'レシピ未登録')}</p>${gs.map(g=>`<div class="metric-row"><span>GAME ${g.number} · ${g.turn==='FIRST'?'先攻':'後攻'}</span>${pill(g.result)}</div>`).join('')}${m.tags.length?`<p>${m.tags.map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</p>`:''}${m.notes?`<p class="prewrap note">${esc(m.notes)}</p>`:''}<div class="dialog-actions"><button class="secondary" data-edit="${id}">編集</button><button class="danger" data-delete="${id}">削除</button></div>`);}
function live(){const rows=[...document.querySelectorAll('.game-row')].filter(x=>x.style.display!=='none');const gs=rows.map(x=>({result:x.querySelector('[data-kind=result].selected')?.dataset.value})).filter(x=>x.result);const manual=$('#override')?.value;$('#live-result').textContent=manual?`手動: ${manual}`:gs.length?`自動: ${resultOf(gs)}`:'結果を選択';}
function changeFormat(){const single=$('#format').value==='SINGLE';document.querySelectorAll('.game-row').forEach((x,i)=>{x.style.display=single&&i>0?'none':'';});live();}
async function submit(form){const f=new FormData(form),id=form.id;try{if(id==='deck-form'){await service.addDeck({name:f.get('name'),regulationId:f.get('regulationId'),version:f.get('version'),main:f.get('main'),extra:f.get('extra'),side:f.get('side')});state.pdfDraft=null;toast('デッキを登録しました');state.view='decks';}else if(id==='version-form'){await service.addVersion(form.dataset.deck,Object.fromEntries(f));state.pdfDraft=null;toast('新バージョンを保存しました');state.source=null;}else if(id==='event-form'){await service.addEvent(Object.fromEntries(f));toast('イベントを登録しました');}else if(id==='event-edit-form'){await service.updateEvent(form.dataset.event,Object.fromEntries(f));state.editingEvent=false;toast('イベントを更新しました');}else if(id==='period-form'){const p=await service.addPeriod(Object.fromEntries(f));state.regulation=p.id;toast('レギュレーションを登録しました');}else if(id==='record-form'){const rows=[...document.querySelectorAll('.game-row')].filter(x=>x.style.display!=='none');const games=rows.map(x=>({turn:x.querySelector('[data-kind=turn].selected')?.dataset.value,result:x.querySelector('[data-kind=result].selected')?.dataset.value}));await service.saveBattle({date:f.get('date'),format:f.get('format'),deckName:f.get('deckName'),deckId:f.get('deckId'),deckVersionId:f.get('deckVersionId'),opponent:f.get('opponent'),eventId:f.get('eventId'),games,override:f.get('override'),tags:f.get('tags'),notes:f.get('notes')},state.editing);toast('対戦を保存しました');state.editing=null;state.view='home';}await refresh();scheduleCloudSync();}catch(e){toast(e.message||'保存に失敗しました');}}
document.addEventListener('submit',e=>{if(['deck-form','version-form','event-form','event-edit-form','record-form','period-form'].includes(e.target.id)){e.preventDefault();submit(e.target);}else if(e.target.id==='cloud-config-form'){e.preventDefault();try{const cfg=Object.fromEntries(new FormData(e.target));saveCloudConfig(cfg);location.reload();}catch(err){toast(err.message);}}else if(e.target.id==='cloud-login-form'){e.preventDefault();const btn=e.target.querySelector('button[type=submit]');btn.disabled=true;cloud.sendLink(new FormData(e.target).get('email')).then(()=>toast('ログイン用リンクをメールへ送りました')).catch(err=>toast(err.message)).finally(()=>{btn.disabled=false;});}});
document.addEventListener('click',async e=>{const target=e.target.closest('button');if(!target)return;const d=target.dataset;
 if(d.nav){state.view=d.nav;state.editing=null;state.eventDetail=null;state.editingEvent=false;state.deckDetail=null;state.originEvent=null;state.focusVersion=null;state.source=null;render();return;}
 if(d.comboToggle){setComboMenu(d.comboToggle,$(`#${d.comboToggle}-options`)?.hidden,$(`#${d.comboToggle}`)?.value||'');return;}
 if(d.comboOption){$(`#${d.comboOption}`).value=d.comboName;if(d.comboOption==='deck')syncDeckVersion(d.comboId);setComboMenu(d.comboOption,false);return;}
 if(target.id==='settings-btn'){state.view='settings';render();return;}
 if(d.back){if(d.back==='events'){state.eventDetail=null;state.editingEvent=false;}else if(d.back==='event-detail'){state.view='events';state.eventDetail=state.originEvent;state.deckDetail=null;state.originEvent=null;state.focusVersion=null;}else {state.deckDetail=null;state.originEvent=null;state.focusVersion=null;}state.source=null;render();return;}
 if(d.detail){detail(d.detail);return;}
 if(d.event){state.eventDetail=d.event;state.editingEvent=false;render();return;}
 if(d.eventDeck){const e=state.data.events.find(x=>x.id===state.eventDetail);state.focusVersion=eventRecipeVersion(state.data.matches,e?.id,d.eventDeck);state.originEvent=e?.id||null;state.eventDetail=null;state.view='decks';state.deckDetail=d.eventDeck;render();return;}
 if(d.editEvent!==undefined){state.editingEvent=true;render();return;}
 if(d.cancelEventEdit!==undefined){state.editingEvent=false;render();return;}
 if(d.cardSearch){state.originEvent=null;state.focusVersion=null;state.cardSearch=d.cardSearch;state.deckDetail=null;state.view='decks';render();return;}
 if(d.deckDetail){state.originEvent=null;state.focusVersion=null;state.deckDetail=d.deckDetail;render();return;}
 if(d.copyVersion){state.source=d.copyVersion;state.pdfDraft=null;render();$('#new-version')?.scrollIntoView({behavior:'smooth',block:'start'});return;}
 if(d.game){const group=target.closest('.seg');group.querySelectorAll('button').forEach(b=>b.classList.remove('selected'));target.classList.add('selected');live();return;}
 if(d.close!==undefined){$('#dialog').close();return;}
 if(d.edit){$('#dialog').close();state.editing=d.edit;state.view='record';render();return;}
 if(target.id==='cloud-sync'){await runCloudSync();return;}
 if(target.id==='cloud-signout'){try{await cloud.signOut();toast('ログアウトしました');await refresh();}catch(err){toast(err.message);}return;}
 if(target.id==='cloud-reset-device'){if(cloud.busy){toast('同期終了後に操作してください');return;}if(!confirm('この端末の戦績・デッキ・イベント・同期履歴をすべて削除しますか？ クラウド上のデータは残ります。先にJSONを保存してください。'))return;try{clearTimeout(syncTimer);await cloud.signOut();await repo.clearLocalAccount();state.cloudError='';state.view='home';toast('端末データと同期履歴を消去しました');await refresh();}catch(err){toast(err.message);}return;}
 if(d.delete){if(!confirm('この対戦記録と各ゲームを削除しますか？'))return;try{await service.deleteBattle(d.delete);$('#dialog').close();toast('記録を削除しました');await refresh();scheduleCloudSync();}catch(err){toast(err.message);}return;}
 if(d.periodSelect){state.regulation=d.periodSelect;render();window.scrollTo({top:0,behavior:'smooth'});return;}
 if(d.periodDelete){if(!confirm('このレギュレーションを削除しますか？ 対戦記録は残ります。'))return;try{await service.deletePeriod(d.periodDelete);if(state.regulation===d.periodDelete)state.regulation='';toast('レギュレーションを削除しました');await refresh();scheduleCloudSync();}catch(err){toast(err.message);}return;}
 if(d.cancelEdit!==undefined){state.editing=null;render();return;}
 if(target.id==='clear-all'){if(cloud.busy){toast('同期終了後に操作してください');return;}const modal=dialog('<h2>保存データをすべて削除</h2><p>対戦・ゲーム・デッキ・レシピ・イベント・タグ・独自のレギュレーション・表示設定を削除します。ログイン中は次回同期時にクラウド上の記録も削除されます。元には戻せません。先にJSONバックアップを保存してください。</p><div class="dialog-actions"><button class="secondary" data-close>キャンセル</button><button class="danger" id="confirm-clear-all">すべて削除する</button></div>');modal.onclick=async ev=>{if(ev.target.closest('[data-close]')){modal.close();return;}if(ev.target.id!=='confirm-clear-all')return;ev.target.disabled=true;try{await service.deleteAllData(settings);modal.close();state.view='home';state.period='all';state.regulation='';state.venue='';state.eventVenue='';state.cardSearch='';state.eventDetail=null;state.editingEvent=false;state.deckDetail=null;state.originEvent=null;state.focusVersion=null;state.pdfDraft=null;toast('保存データをすべて削除しました');await refresh();scheduleCloudSync();}catch(err){ev.target.disabled=false;toast(err.message||'削除に失敗しました');}};return;}
 if(target.id==='export'){download(JSON.stringify(await service.exportBackup(),null,2),`ocg-record-backup-${today().replaceAll('-','')}.json`,'application/json');toast('バックアップを保存しました');}
 if(target.id==='csv-export'){const a=analyze(state.data,{key:state.period||'all',from:state.from,to:state.to,venue:state.venue,regulation:state.regulation});download(battlesCsv(state.data,a.matches),`ocg-record-battles-${today().replaceAll('-','')}.csv`,'text/csv;charset=utf-8');toast(`${a.matches.length}件の対戦をCSV出力しました`);}
});
document.addEventListener('change',async e=>{const t=e.target;
 if(t.id==='deck-pdf-file'&&t.files[0]){const parent=state.deckDetail?'#version-form':'#deck-form',prior={};for(const name of ['name','version']){const input=document.querySelector(`${parent} [name="${name}"]`);if(input?.value?.trim())prior[name]=input.value;}try{toast('PDFを読み取り中…');const draft=await readDeckPdf(t.files[0]);state.pdfDraft={...draft,deckId:state.deckDetail||null};state.source=null;render();for(const [name,value] of Object.entries(prior)){const input=document.querySelector(`${parent} [name="${name}"]`);if(input)input.value=value;}toast('レシピを読み込みました。内容を確認してください。');}catch(err){toast(err.message||'PDFを読み込めませんでした');}return;}
 if(t.id==='format'){changeFormat();}
 if(t.name==='date'&&t.closest('#event-form,#event-edit-form')){const p=regulationForDate(t.value,state.data.periods);$('#regulationId').value=p?.id||'';}
 if(t.id==='override')live();
 if(t.id==='analysis-period'){state.period=t.value;render();}
 if(t.id==='analysis-regulation'){state.regulation=t.value;render();}
 if(t.id==='analysis-venue'){state.venue=t.value;render();}
 if(t.id==='event-venue'){state.eventVenue=t.value;render();}
 if(t.id==='period-from'||t.id==='period-to'){state[t.id==='period-from'?'from':'to']=t.value;render();}
 if(t.id==='theme'){settings.save({theme:t.value});theme();}
 if(t.id==='import-file'&&t.files[0]){try{const data=validateBackup(JSON.parse(await t.files[0].text()));const counts=STORES.map(s=>`${s}: ${data[s].length}`).join(' / ');const modal=dialog(`<h2>バックアップを復元</h2><p class="muted">${esc(counts)}</p><p>上書きすると現在のデータを消去します。マージは同じIDのデータを読み込んだ内容で更新します。</p><div class="dialog-actions"><button class="secondary" data-import="merge">マージ</button><button class="danger" data-import="replace">上書き</button><button class="secondary" data-close>キャンセル</button></div>`);modal.onclick=async ev=>{const mode=ev.target.closest('[data-import]')?.dataset.import;if(!mode)return;try{await service.importBackup(data,mode);state.period='all';state.regulation='';modal.close();toast('復元しました');await refresh();scheduleCloudSync();}catch(err){toast(err.message||'復元に失敗しました');}};}catch(err){toast(err.message||'JSONを読み込めません');}t.value='';}
});
document.addEventListener('input',e=>{const t=e.target;if(t.id==='opponent'||t.id==='deck'){if(t.id==='deck')syncDeckVersion();setComboMenu(t.id,true,t.value);return;}if(t.id==='deck-card-search'){const start=t.selectionStart,end=t.selectionEnd;state.cardSearch=t.value;const deckList=t.closest('#content');if(deckList){const scroll=window.scrollY;render();const next=$('#deck-card-search');next.focus();next.setSelectionRange(start,end);window.scrollTo(0,scroll);}return;}if(!t.matches('textarea[name="main"],textarea[name="extra"],textarea[name="side"]'))return;const form=t.closest('#deck-form,#version-form');if(!form)return;try{const count=z=>parseCards(form.querySelector(`textarea[name="${z}"]`).value).reduce((n,c)=>n+c.count,0);form.querySelector('.recipe-counts').textContent=`編集中の枚数：MAIN ${count('main')} / EXTRA ${count('extra')} / SIDE ${count('side')}`;}catch{form.querySelector('.recipe-counts').textContent='カード名と枚数の書式を確認してください。';}});
function syncDeckVersion(chosenId=''){
 const name=$('#deck')?.value||'',matches=matchingDecks(state.data.decks,name);
 const deck=chosenId?matches.find(x=>x.id===chosenId):matches.length===1?matches[0]:null;
 const hidden=$('#deckId'),select=$('#deckVersionId'),hint=$('#deck-version-hint');
 if(!hidden||!select||!hint)return;
 hidden.value=deck?.id||'';
 const versions=deck?versionsForDeck(state.data.deckVersions,deck.id):[];
 const previous=select.value;
 select.disabled=!versions.length;
 const old=state.data.matches.find(x=>x.id===state.editing),allowUnversioned=old?.deckId===deck?.id&&!old.deckVersionId;
 select.innerHTML=versions.length?(allowUnversioned?option('','対戦当時はレシピ未登録',previous):'')+versions.map(v=>option(v.id,v.label,previous&&versions.some(x=>x.id===previous)?previous:allowUnversioned?'':versions[0].id)).join(''):option('','レシピ未登録（選択不要）','');
 hint.textContent=versions.length?`${versions.length}件のレシピから選択できます。`:matches.length>1?'同名のデッキがあります。候補から選択してください。':name.trim()&&!deck?'この名前でデッキを登録して戦績を保存します。':'レシピがないデッキも版なしで保存できます。';
}
function setComboMenu(kind,show,query=''){
 const panel=$(`#${kind}-options`),input=$(`#${kind}`),toggle=$(`#${kind}-toggle`);
 if(!panel||!input||!toggle)return;
 const choices=[...panel.querySelectorAll('[data-combo-option]')],visible=new Set(suggestOpponents(choices.map(b=>b.dataset.comboName),query));
 let count=0;
 for(const b of choices){const name=b.dataset.comboName;b.hidden=!visible.has(name);if(!b.hidden){count++;const title=b.querySelector('.combo-option-name'),at=name.toLocaleLowerCase('ja').indexOf(query.toLocaleLowerCase('ja'));title.innerHTML=query&&at>=0?`${esc(name.slice(0,at))}<mark>${esc(name.slice(at,at+query.length))}</mark>${esc(name.slice(at+query.length))}`:esc(name);}}
 panel.hidden=!show;input.setAttribute('aria-expanded',String(!!show));toggle.setAttribute('aria-expanded',String(!!show));
 const hint=$(`#${kind}-hint`);if(hint&&kind==='opponent')hint.textContent=show?`${count}件の候補。候補をタップするか新しい名前を入力してください。`:'入力すると候補を絞り込めます。';
 if(show&&!count&&choices.length)panel.dataset.empty='true';else delete panel.dataset.empty;
}
document.addEventListener('focusin',e=>{if(e.target.id==='opponent'||e.target.id==='deck')setComboMenu(e.target.id,true,e.target.value);});
document.addEventListener('click',e=>{if(!e.target.closest('.combo-wrap'))for(const kind of ['opponent','deck'])setComboMenu(kind,false);});
document.addEventListener('keydown',e=>{const kind=e.target.closest('.combo-wrap')?.dataset.combo;if(!kind)return;if(e.target.id===kind&&e.key==='ArrowDown'){setComboMenu(kind,true,e.target.value);$(`#${kind}-options`)?.querySelector('button:not([hidden])')?.focus();e.preventDefault();}if(e.key==='Escape'){setComboMenu(kind,false);$(`#${kind}`)?.focus();}});
try{await repo.ready;await refresh();if(cloudConfig())cloud.connect().then(()=>{if(cloud.user)scheduleCloudSync();}).catch(err=>{state.cloudError=err.message;cloud.listener();});window.addEventListener('online',scheduleCloudSync);document.addEventListener('visibilitychange',()=>{if(!document.hidden)scheduleCloudSync();});}catch(e){$('#content').innerHTML=`<div class="empty">データベースを開けません。ブラウザのプライベートモードやストレージ設定をご確認ください。<br>${esc(e.message)}</div>`;}
