import {uid,stamp,STORES} from './storage.js';
export const today=()=>{const d=new Date(),z=d.getTimezoneOffset()*60000;return new Date(d-z).toISOString().slice(0,10);};
export const clean=s=>String(s??'').trim();
export function resultOf(games){let w=0,l=0;for(const g of games){if(g.result==='WIN')w++;if(g.result==='LOSS')l++;}return w>l?'WIN':l>w?'LOSS':'DRAW';}
export function parseCards(value){const lines=String(value||'').split(/\r?\n/),out=[];for(const line of lines){const s=line.trim();if(!s)continue;const m=s.match(/^(.*?)\s*(?:[×xX＊*]\s*(\d+))?$/);const name=clean(m[1]),count=Number(m[2]||1);if(!name||count<1||count>99)throw Error('カード名と枚数を確認してください');const existing=out.find(x=>x.name===name);if(existing)existing.count+=count;else out.push({id:uid(),cardId:null,name,count});}return out;}
export function validateBackup(data){if(!data||typeof data!=='object'||data.schemaVersion!==1)throw Error('対応していないバックアップ形式です');for(const s of STORES){if(!Array.isArray(data[s])||data[s].some(x=>!x||typeof x.id!=='string'||!x.id))throw Error(`${s} のデータが不正です`);}const ids={};for(const s of STORES){ids[s]=new Set(data[s].map(x=>x.id));if(ids[s].size!==data[s].length)throw Error(`${s} のIDが重複しています`);}for(const m of data.matches){if(m.deckId&&!ids.decks.has(m.deckId))throw Error('存在しないデッキを参照する対戦があります');if(m.deckVersionId&&!ids.deckVersions.has(m.deckVersionId))throw Error('存在しないレシピ版を参照する対戦があります');if(m.eventId&&!ids.events.has(m.eventId))throw Error('存在しないイベントを参照する対戦があります');}for(const g of data.games)if(!ids.matches.has(g.matchId))throw Error('孤立したゲームがあります');for(const v of data.deckVersions)if(!ids.decks.has(v.deckId))throw Error('孤立したレシピ版があります');return data;}
export class AppService{
 constructor(repo){this.repo=repo;}
 async all(){return this.repo.snapshot();}
 async addDeck({name,type,version,notes,main,extra,side}){name=clean(name);if(!name)throw Error('デッキ名を入力してください');const now=stamp(),deck={id:uid(),userId:null,name,type:clean(type),notes:clean(notes),createdAt:now,updatedAt:now};const v=this.version(deck.id,{version,notes,main,extra,side});await this.repo.put('decks',deck);await this.repo.put('deckVersions',v);return deck;}
 version(deckId,{version,notes,main,extra,side}){const now=stamp();return {id:uid(),userId:null,deckId,label:clean(version)||today(),notes:clean(notes),cards:{main:parseCards(main),extra:parseCards(extra),side:parseCards(side)},createdAt:now,updatedAt:now};}
 async addVersion(deckId,fields){const deck=await this.repo.get('decks',deckId);if(!deck)throw Error('デッキが見つかりません');const v=this.version(deckId,fields);await this.repo.put('deckVersions',v);deck.updatedAt=stamp();await this.repo.put('decks',deck);return v;}
 async addEvent(fields){const name=clean(fields.name);if(!name)throw Error('イベント名を入力してください');const now=stamp();const event={id:uid(),userId:null,name,date:fields.date||today(),venue:clean(fields.venue),type:clean(fields.type)||'その他',deckId:fields.deckId||null,rank:clean(fields.rank),participants:fields.participants?Number(fields.participants):null,notes:clean(fields.notes),createdAt:now,updatedAt:now};await this.repo.put('events',event);return event;}
 async saveBattle(input,id=null){const deck=await this.repo.get('decks',input.deckId);if(!deck)throw Error('使用デッキを選んでください');const version=await this.repo.get('deckVersions',input.deckVersionId);if(!version||version.deckId!==deck.id)throw Error('デッキバージョンを選んでください');if(input.eventId&&!await this.repo.get('events',input.eventId))throw Error('イベントが見つかりません');const opponent=clean(input.opponent);if(!opponent)throw Error('相手デッキを入力してください');if(!['MATCH','SINGLE'].includes(input.format))throw Error('対戦形式が不正です');const games=input.games.filter(g=>g.result);if(!games.length||games.length>(input.format==='SINGLE'?1:3))throw Error('ゲーム結果を入力してください');if(games.some(g=>!['FIRST','SECOND'].includes(g.turn)||!['WIN','LOSS','DRAW'].includes(g.result)))throw Error('先後と勝敗を確認してください');const result=input.override||resultOf(games);if(!['WIN','LOSS','DRAW','DOUBLE_LOSS'].includes(result))throw Error('対戦結果が不正です');const now=stamp(),old=id?await this.repo.get('matches',id):null;if(id&&!old)throw Error('対象の対戦が見つかりません');const tags=[...new Set(String(input.tags||'').split(/[,、\n]/).map(clean).filter(Boolean))];const match={id:id||uid(),userId:null,eventId:input.eventId||null,deckId:deck.id,deckVersionId:version.id,opponentDeckName:opponent,opponentDeckId:null,format:input.format,playedAt:input.date||today(),result,resultSource:input.override?'manual':'auto',notes:clean(input.notes),tags,createdAt:old?.createdAt||now,updatedAt:now};let n=0;const gameRows=games.map(g=>({id:uid(),userId:null,matchId:match.id,number:++n,turn:g.turn,result:g.result,createdAt:now,updatedAt:now}));const existing=await this.repo.list('tags');const newTags=tags.filter(name=>!existing.some(t=>t.name===name)).map(name=>({id:uid(),userId:null,name,createdAt:now,updatedAt:now}));await this.repo.saveBattleGraph(match,gameRows,newTags);return match;}
 async deleteBattle(id){await this.repo.deleteBattleGraph(id);}
 async exportBackup(){return {schemaVersion:1,exportedAt:stamp(),...await this.repo.snapshot()};}
 async importBackup(data,mode){validateBackup(data);if(mode==='replace')await this.repo.replaceAll(data);else if(mode==='merge')await this.repo.merge(data);else throw Error('復元方法が不正です');}
}
export const pct=(w,n)=>n?`${(w/n*100).toFixed(1).replace(/\.0$/,'')}%`:'—';
export function stats(matches,games){const tally=xs=>({total:xs.length,win:xs.filter(x=>x.result==='WIN').length,loss:xs.filter(x=>['LOSS','DOUBLE_LOSS'].includes(x.result)).length,draw:xs.filter(x=>x.result==='DRAW').length});const m=tally(matches),g=tally(games);return {matches:{...m,rate:pct(m.win,m.total)},games:{...g,rate:pct(g.win,g.total)}};}
