import assert from 'node:assert/strict';
import {CALCULATOR_CSV_HEADERS,parseCalculatorCsv,planCalculatorImport} from '../js/calculatorImport.js';
import {AppService} from '../js/services.js';
import {STORES} from '../js/storage.js';

const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const empty=()=>Object.fromEntries(STORES.map(store=>[store,[]]));
const csv=[CALCULATOR_CSV_HEADERS.join(','),`${id(1)},2026-09-24,MATCH,1,p2,p1`,`${id(1)},2026-09-24,MATCH,2,p1,DRAW`,`${id(1)},2026-09-24,MATCH,3,p2,p2`,`${id(2)},2026-09-24,SINGLE,1,p1,p2`].join('\r\n');
const records=parseCalculatorCsv(csv);
assert.equal(records.length,2);
const source=empty();source.decks.push({id:id(3),name:'烙印'});source.deckVersions.push({id:id(4),deckId:id(3),label:'v1'});
const inputs=[{recordId:id(1),ownPlayer:'p2',deckName:'烙印',deckVersionId:id(4),opponentDeck:'トゥーン',eventName:'ランキングデュエル',venue:'店舗A',notes:'ETで両敗',override:'DOUBLE_LOSS'},{recordId:id(2),ownPlayer:'p1',deckName:'烙印',deckVersionId:id(4),opponentDeck:'エルフェンノーツ',eventName:'ランキングデュエル',venue:'店舗A'}];
const {data,summary}=planCalculatorImport(csv,inputs,source);
assert.deepEqual(summary,{imported:2,skipped:0,createdDecks:0,createdEvents:1});
assert.equal(data.matches[0].deckVersionId,id(4));
assert.equal(data.matches[0].result,'DOUBLE_LOSS');
assert.equal(data.matches[0].resultSource,'manual');
assert.equal(data.matches[0].notes,'ETで両敗');
assert.equal(data.matches[0].eventId,data.matches[1].eventId);
assert.deepEqual(data.games.filter(g=>g.matchId===id(1)).map(g=>[g.turn,g.result]),[['FIRST','LOSS'],['SECOND','DRAW'],['FIRST','WIN']]);
assert.equal(data.matches[1].result,'LOSS');
assert.equal(data.matches[1].format,'SINGLE');
const second=planCalculatorImport(csv,[],data);
assert.deepEqual(second.summary,{imported:0,skipped:2,createdDecks:0,createdEvents:0});
assert.deepEqual(second.data,data);
const newDeck=planCalculatorImport(csv,[{...inputs[0],deckName:'新デッキ',deckVersionId:''},{...inputs[1],deckVersionId:''}],empty());
assert.equal(newDeck.summary.createdDecks,2);
assert.equal(newDeck.data.matches[0].deckVersionId,null);
const bad=csv.replace('MATCH,2,p1,DRAW','MATCH,1,p1,DRAW');
assert.throws(()=>parseCalculatorCsv(bad),/GAME番号が重複/);
assert.throws(()=>parseCalculatorCsv(csv.replace(`${id(2)},2026-09-24,SINGLE,1,p1,p2`,`${id(2)},2026-09-24,SINGLE,2,p1,p2`)),/GAME番号/);
assert.throws(()=>parseCalculatorCsv(csv.replace('p2,p1','p2,?')),/先攻・勝者/);
assert.throws(()=>parseCalculatorCsv(csv+',LP'),/列数が一致/);
assert.throws(()=>parseCalculatorCsv(csv.replace('firstPlayer,winner','firstPlayer,lifeDelta')),/計算ツールの戦績CSV/);
assert.throws(()=>planCalculatorImport(csv,[{...inputs[0],opponentDeck:''},inputs[1]],source),/相手デッキ/);
assert.throws(()=>planCalculatorImport(csv,[{...inputs[0],eventId:id(9)},inputs[1]],source),/同時に指定/);
assert.deepEqual(source.matches,[]);
let commits=0;
const app=new AppService({snapshot:async()=>source,replaceAllIfUnchanged:async()=>{commits++;return true;}});
assert.equal((await app.importCalculatorCsv(csv,inputs)).imported,2);
assert.equal(commits,1);
const conflict=new AppService({snapshot:async()=>source,replaceAllIfUnchanged:async()=>false});
await assert.rejects(conflict.importCalculatorCsv(csv,inputs),/記録が更新されました/);
console.log('PASS: calculator CSV mapping, user metadata, deduplication, malformed input, atomic save');
