import assert from 'node:assert/strict';
import {reconcile,emptySnapshot,fingerprint,SupabaseCloudRepository,CloudController,saveCloudConfig,cloudConfig,DEFAULT_CLOUD_CONFIG} from '../js/cloud.js';
const storage=new Map();globalThis.localStorage={getItem:key=>storage.get(key)||null,setItem:(key,value)=>storage.set(key,value)};
assert.deepEqual(cloudConfig(),DEFAULT_CLOUD_CONFIG);
assert.throws(()=>saveCloudConfig({url:'http://example.com',key:'abc'}),/URL/);
assert.throws(()=>saveCloudConfig({url:'https://demo.supabase.co',key:'sb_secret_bad'}),/publishable key/);
saveCloudConfig({url:'https://demo.supabase.co/',key:'sb_publishable_example'});
assert.equal(cloudConfig().url,'https://demo.supabase.co');
const owner='11111111-1111-4111-8111-111111111111',id='22222222-2222-4222-8222-222222222222';
const first={id,userId:null,name:'烙印',updatedAt:'2026-09-20T00:00:00Z'};
const local=emptySnapshot();local.decks=[first];
const initial=reconcile(local,[],{},owner,'2026-09-24T00:00:00Z');
assert.equal(initial.push.length,1);assert.equal(initial.push[0].body.userId,owner);
const remote=[{store:'decks',id,body:initial.merged.decks[0],updated_at:first.updatedAt,deleted_at:null}];
const clean=reconcile(initial.merged,remote,initial.baseline,owner);
assert.equal(clean.push.length,0);
const removed=emptySnapshot(),tombstone=reconcile(removed,remote,initial.baseline,owner,'2026-09-24T00:00:00Z');
assert.equal(tombstone.push.length,1);assert.equal(tombstone.push[0].deleted_at,'2026-09-24T00:00:00Z');
assert.equal(tombstone.merged.decks.length,0);
const remoteDelete=reconcile(initial.merged,[{...remote[0],body:null,deleted_at:'2026-09-23T00:00:00Z',updated_at:'2026-09-23T00:00:00Z'}],initial.baseline,owner);
assert.equal(remoteDelete.merged.decks.length,0);assert.equal(remoteDelete.push.length,0);
const edited=emptySnapshot();edited.decks=[{...first,userId:owner,name:'烙印改',updatedAt:'2026-09-24T00:00:00Z'}];
const conflict=reconcile(edited,[{...remote[0],body:{...remote[0].body,name:'烙印旧'},updated_at:'2026-09-21T00:00:00Z'}],initial.baseline,owner);
assert.equal(conflict.merged.decks[0].name,'烙印改');assert.equal(conflict.conflicts.length,1);
assert.equal(fingerprint({a:{z:1,b:2}}),fingerprint({a:{b:2,z:1}}));
const callLog=[];const client={from(table){assert.equal(table,'ocg_records');return {select(){return this;},eq(field,value){assert.equal(field,'user_id');assert.equal(value,owner);return this;},order(){return this;},async range(from,to){callLog.push([from,to]);return {data:from===0?Array.from({length:500},(_,n)=>({...remote[0],id:String(n)})):[],error:null};},async upsert(rows,options){assert.equal(options.onConflict,'user_id,store,id');callLog.push(rows.length);return {error:null};}};}};
const repo=new SupabaseCloudRepository(client,owner);
assert.equal((await repo.snapshotRows()).length,500);assert.deepEqual(callLog.slice(0,2),[[0,499],[500,999]]);
await repo.upsertRows(Array.from({length:205},()=>initial.push[0]));assert.deepEqual(callLog.slice(2),[100,100,5]);
const cached={ownerId:owner,baseline:initial.baseline};
const guarded=new CloudController({getSyncMeta:async()=>cached});guarded.user={id:'33333333-3333-4333-8333-333333333333'};
await assert.rejects(guarded.sync(),/別のアカウント/);
const persisted={getSyncMeta:async()=>null,snapshot:async()=>local,replaceAllIfUnchanged:async(expected,merged)=>{assert.equal(expected.decks.length,1);assert.equal(merged.decks[0].userId,owner);return false;},putSyncMeta:async()=>{throw Error('should not commit');}};
const retry=new CloudController(persisted);retry.user={id:owner};retry.client={from(){return {select(){return this;},eq(){return this;},order(){return this;},async range(){return {data:[],error:null};},async upsert(){return {error:null};}};}};
await assert.rejects(retry.sync(),/もう一度同期/);
console.log('PASS: initial cloud upload, no-op, two-way deletions, conflicts, pagination and batches');
