import assert from 'node:assert/strict';
import {battlesCsv} from '../js/analysisService.js';
import {parseBattlesCsv,planBattlesCsv} from '../js/csvImport.js';
import {AppService} from '../js/services.js';
import {STORES} from '../js/storage.js';

const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const empty=()=>Object.fromEntries(STORES.map(store=>[store,[]]));
const original=empty();
original.decks.push({id:id(1),name:'烙印, "試作"'});
original.deckVersions.push({id:id(2),deckId:id(1),label:'v1',cards:{main:[],extra:[],side:[]}});
original.events.push({id:id(3),name:'地区大会',venue:'店舗A',date:'2026-09-24'});
original.matches.push({id:id(4),deckId:id(1),deckVersionId:id(2),eventId:id(3),format:'MATCH',playedAt:'2026-09-24',opponentDeckName:'=相手',result:'DOUBLE_LOSS',resultSource:'manual',notes:'1行目,"引用"\n2行目',tags:['ET','決勝']});
original.games.push({id:id(5),matchId:id(4),number:1,turn:'SECOND',result:'LOSS'},{id:id(6),matchId:id(4),number:2,turn:'FIRST',result:'DRAW'});
const csv=battlesCsv(original,original.matches);
assert.equal(parseBattlesCsv(csv).length,1);
const first=planBattlesCsv(csv,empty());
assert.equal(first.summary.imported,1);
assert.equal(first.summary.createdDecks,1);
assert.equal(first.summary.createdEvents,1);
assert.equal(first.summary.unlinkedVersions,1);
assert.equal(first.data.matches[0].id,id(4));
assert.equal(first.data.matches[0].opponentDeckName,'=相手');
assert.equal(first.data.matches[0].notes,original.matches[0].notes);
assert.equal(first.data.matches[0].result,'DOUBLE_LOSS');
assert.deepEqual(first.data.matches[0].tags,['ET','決勝']);
assert.deepEqual(first.data.games.map(g=>g.id),[id(5),id(6)]);
assert.equal(first.data.matches[0].deckVersionId,null);
assert.equal(first.data.tags.length,2);
const again=planBattlesCsv(csv,first.data);
assert.deepEqual(again.summary,{imported:0,skipped:1,createdDecks:0,createdEvents:0,unlinkedVersions:0});
assert.deepEqual(again.data,first.data);
const withVersion=empty();withVersion.decks.push(original.decks[0]);withVersion.deckVersions.push(original.deckVersions[0]);
assert.equal(planBattlesCsv(csv,withVersion).data.matches[0].deckVersionId,id(2));
assert.throws(()=>parseBattlesCsv(csv.replace(`"${id(6)}"`,`"${id(5)}"`)),/ゲームIDが重複/);
const lines=csv.trimEnd().split('\r\n');
const columns=lines[0].split(',');
const changed=lines[2].split(',');
changed[columns.indexOf('matchResult')]='"WIN"';
assert.throws(()=>parseBattlesCsv([lines[0],lines[1],changed.join(',')].join('\r\n')),/同じ対戦IDの情報が一致/);
assert.throws(()=>parseBattlesCsv(csv+'"unterminated'),/引用符が閉じられていません/);
assert.throws(()=>parseBattlesCsv(csv.replace('"MATCH"','"MATCH"extra')),/引用符の後に余分な文字/);
const colliding=empty();colliding.games.push({id:id(5),matchId:id(99)});
assert.throws(()=>planBattlesCsv(csv,colliding),/別の対戦とゲームID/);
let replaced=0;
const repo={snapshot:async()=>empty(),replaceAllIfUnchanged:async(_old,data)=>{replaced++;assert.equal(data.matches.length,1);return true;}};
const service=new AppService(repo);
assert.equal((await service.importBattlesCsv(csv)).imported,1);
assert.equal(replaced,1);
const rejected=new AppService({snapshot:async()=>empty(),replaceAllIfUnchanged:async()=>false});
await assert.rejects(rejected.importBattlesCsv(csv),/記録が更新されました/);
console.log('PASS: CSV export/import roundtrip, quoted fields, duplicates, invalid CSV, atomic commit');
