import assert from 'node:assert/strict';
import {parseCards,AppService} from '../js/services.js';
import {formatCards,groupCards} from '../js/cardTypes.js';
import {analyze} from '../js/analysisService.js';
import {renderAnalysis} from '../js/analysisView.js';
import {DEFAULT_PERIODS} from '../js/defaultPeriods.js';
import {STORES} from '../js/storage.js';
const cards=parseCards('【魔法】\n1《烙印融合》\n2《烙印開幕》\n【モンスター】\n1《アルバスの落胤》\n2《灰流うらら》\n【罠】\n1《無限泡影》');
assert.deepEqual(groupCards(cards).map(x=>x.label),['モンスター','魔法','罠']);
assert.deepEqual(groupCards(cards)[0].cards.map(x=>x.name),['アルバスの落胤','灰流うらら']);
assert.deepEqual(groupCards(cards)[1].cards.map(x=>x.name),['烙印開幕','烙印融合']);
assert.deepEqual(parseCards(formatCards(cards)).map(x=>[x.name,x.type,x.count]).sort(),cards.map(x=>[x.name,x.type,x.count]).sort());
assert.equal(groupCards([{name:'旧カード',count:1}])[0].label,'未分類');
assert.equal(parseCards('1《EXモンスター》','MONSTER')[0].type,'MONSTER');
const repo={tables:Object.fromEntries(STORES.map(s=>[s,new Map()])),async list(s){return [...this.tables[s].values()];},async get(s,id){return this.tables[s].get(id);},async put(s,row){this.tables[s].set(row.id,structuredClone(row));},async snapshot(){return Object.fromEntries(STORES.map(s=>[s,[...this.tables[s].values()]]));}};
const service=new AppService(repo),reg=DEFAULT_PERIODS.find(p=>p.label==='2607');
const deck=await service.addDeck({name:'烙印',regulationId:reg.id,version:'v1',main:'1《アルバスの落胤》'});
const event=await service.addEvent({name:'大会',date:'2026-08-01',venue:'旧店',regulationId:reg.id,deckId:deck.id,notes:'元メモ'});
const original=await repo.get('events',event.id);
const changed=await service.updateEvent(event.id,{name:'大会改',date:'2026-08-08',venue:'新店',regulationId:reg.id,deckId:deck.id,rank:'2位',participants:'16',notes:'修正'});
assert.equal(changed.id,event.id);assert.equal(changed.createdAt,original.createdAt);assert.equal(changed.date,'2026-08-08');assert.equal(changed.venue,'新店');assert.equal(changed.participants,16);
await assert.rejects(service.updateEvent(event.id,{name:' ',regulationId:reg.id}),/イベント名/);
await assert.rejects(service.updateEvent('missing',{name:'大会',regulationId:reg.id}),/見つかりません/);
const match={id:'m',format:'MATCH',playedAt:'2026-08-08',eventId:event.id,deckId:deck.id,deckVersionId:'v',result:'WIN',opponentDeckName:'相手',tags:[]};
await repo.put('matches',match);
const base=await repo.snapshot();
assert.equal(analyze(base,{key:'custom',from:'2026-08-01',to:'2026-08-31',regulation:reg.id}).match.total,1);
assert.equal(analyze(base,{key:'custom',from:'2026-09-01',to:'2026-09-30',regulation:reg.id}).match.total,0);
const legacy={...base,events:base.events.map(e=>({...e,regulationId:null})),decks:base.decks.map(d=>({...d,regulationId:null}))};
assert.equal(analyze(legacy,{regulation:reg.id}).match.total,1);
const other=DEFAULT_PERIODS.find(p=>p.label==='2604');
assert.equal(analyze({...base,events:base.events.map(e=>({...e,regulationId:other.id}))},{regulation:reg.id}).match.total,0);
const html=renderAnalysis(base,{period:'30',regulation:reg.id});
assert(html.includes('id="analysis-period"'));assert(html.includes('id="analysis-regulation"'));assert(!html.includes('集計期間・レギュレーション'));
console.log('PASS: card kind order and roundtrip, event updates, independent analysis filters');
