import assert from 'node:assert/strict';
import {DEFAULT_PERIODS,allPeriods,regulationForDate,regulationLabel} from '../js/defaultPeriods.js';
import {periodBounds,analyze,battlesCsv} from '../js/analysisService.js';
import {AppService} from '../js/services.js';
import {STORES} from '../js/storage.js';
const p=DEFAULT_PERIODS.find(x=>x.startDate==='2026-07-01');
assert.deepEqual([p.label,p.endDate],['2607','2026-09-30']);
assert.equal(DEFAULT_PERIODS.at(-1).startDate,'2026-10-01');
assert.equal(DEFAULT_PERIODS.at(-1).endDate,'9999-12-31');
for(let i=1;i<DEFAULT_PERIODS.length;i++)assert.equal(new Date(DEFAULT_PERIODS[i-1].endDate).getTime()+86400000,new Date(DEFAULT_PERIODS[i].startDate).getTime());
assert.deepEqual(periodBounds(`period:${p.id}`),[p.startDate,p.endDate]);
assert.equal(regulationLabel('2000-05-15'),'000515');
assert.equal(regulationForDate('2026-09-24').id,p.id);
assert.equal(allPeriods([{id:'custom'}]).length,DEFAULT_PERIODS.length+1);
const repo={tables:Object.fromEntries(STORES.map(x=>[x,new Map()])),async put(s,x){this.tables[s].set(x.id,x);},async list(s){return [...this.tables[s].values()];},async snapshot(){return Object.fromEntries(STORES.map(s=>[s,[...this.tables[s].values()]]));},async clearAll(){for(const s of STORES)this.tables[s].clear();}};
const svc=new AppService(repo);
const deck=await svc.addDeck({name:'烙印',type:'旧タイプ',notes:'旧メモ',regulationId:p.id,version:'v1',main:'1《アルバスの落胤》\n2《烙印融合》'});
assert.equal(deck.regulationId,p.id);assert.equal((await repo.list('deckVersions'))[0].cards.main[1].count,2);
assert(!('type' in deck));assert(!('notes' in deck));
assert(!('notes' in (await repo.list('deckVersions'))[0]));
const event=await svc.addEvent({name:'大会',venue:'駅前店',regulationId:p.id,type:'旧種別'});
assert.equal(event.regulationId,p.id);
assert(!('type' in event));
const other=await svc.addEvent({name:'大会2',venue:'中央店'});
await repo.put('matches',{id:'m',eventId:event.id,playedAt:'2026-09-24',format:'MATCH',result:'WIN',deckId:deck.id,deckVersionId:'v',opponentDeckName:'相手',tags:[]});
await repo.put('matches',{id:'n',eventId:other.id,playedAt:'2026-09-24',format:'MATCH',result:'LOSS',deckId:deck.id,deckVersionId:'v',opponentDeckName:'相手',tags:[]});
const data=await repo.snapshot();assert.equal(analyze(data,{venue:'駅前店'}).match.total,1);
assert.equal(analyze(data,{venue:'駅前店'}).match.win,1);
assert(battlesCsv({...data,games:[{id:'g',matchId:'m',number:1,turn:'FIRST',result:'WIN'}]},[data.matches[0]]).includes('"駅前店"'));
await assert.rejects(svc.addDeck({name:'不正',regulationId:'missing'}));
const custom=await svc.addPeriod({startDate:'2030-04-01',endDate:'2030-06-30'});assert.equal(custom.label,'3004');
await svc.addEvent({name:'独自',regulationId:custom.id});await assert.rejects(svc.deletePeriod(custom.id));
let cleared=false;await svc.deleteAllData({clear(){cleared=true;}});
assert(cleared);for(const s of STORES)assert.equal((await repo.list(s)).length,0);
console.log('PASS: default periods, venue filtering, removed fields, full reset');
